### ISSUE TITLE
Use containers for configuring software environment?

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/genomics-workshop#28] opened 2017-10-10 19:25 UTC
In datacarpentry/shell-genomics#49 @standage brought up the idea to create a docker image for the shell-genomics part. This concerns the whole genomics-workshop and not only the shell lesson. I think a Docker image would provide flexibility from the current approach and would be a good way to be able to set up the workshop on a different infrastructure. @standage also offered to spear-head the effort if there is support.

**Comment by fpsom** [comment] 2017-10-18 06:12
@aschuerch I completely agree with this. I wouldn't aim for a single docker image for all tools - this would lead to a bloated image which would require too much time to download. But we could create a compendium of docker images (either existing or new ones), one for each tool in the lesson, that could be used to run the exercises.

**Comment by tracykteal** [comment] 2017-11-09 19:04
This discussion also came up in https://github.com/datacarpentry/wrangling-genomics/issues/75#issuecomment-343191568, so linking them here.

**Comment by ErinBecker** [comment] 2017-11-21 18:06
Not sure if this set of PRs also addresses this issue: https://github.com/datacarpentry/genomics-workshop/issues/31

@aschuerch @tracykteal @fpsom - could you please let me know if this issue should be closed now that the data is available on OSF or if it should stay open?

**Comment by tracykteal** [comment] 2017-11-21 18:21
Thanks, it should stay open. This is related to be able to run the programs as well as have the data.

**Comment by fpsom** [comment] 2017-11-21 20:06
I also agree to keep it open. This relates mostly to Docker as a means (and example) of reproducibility; which will require some extra work in finding/creating the respective images.

As a side note, it would be interesting to have a Carpentries user in [DockerHub](https://hub.docker.com/) as well. Just putting this out there.

**Comment by aschuerch** [comment] 2017-11-22 08:35
I agree it should stay open

**Comment by ErinBecker** [comment] 2018-04-13 16:44
@standage this may be of interest to you.

**Comment by brooksph** [comment] 2018-04-13 22:34
Regarding Docker images for individual tools as @fpsom and @standagem mentioned; the biocontainers project has a nice effort going with approximately 3000 images for various bioinformatics tools including, most if not all, of those in the shell lesson https://biocontainers.pro/registry/#/ . The images are created and maintained by the bioconda project https://github.com/bioconda/bioconda-recipes/tree/master/recipes but anyone can join. It can be a bit difficult to get the hang of creating or modifying the recipes but the bioconda community is very helpful.

**Comment by JasonJWilliamsNY** [comment] 2019-06-01 16:46
The technology maintainer group should handle these requests. I am a maintainer and can help with organizing any and all cloud images and also the data. I think we need to agree on recommendations first on a policy and solution and them implement.

**Comment by pvanheus** [comment] 2019-08-30 11:48
As an alternative to Docker, I have created a Singularity container, with the following definition file. If I find time I'll put it on Singularity Hub:

```
BootStrap: docker
From: continuumio/miniconda3:4.7.10-alpine

%post
    PATH=/opt/conda/bin:$PATH
    export PATH
    apk update 
    cd /opt
    conda install -y -c bioconda -c conda-forge openjdk=8.0.192 fastqc=0.11.7 trimmomatic=0.38 bwa=0.7.17 samtools=1.9 bcftools=1.8 font-ttf-dejavu-sans-mono=2.37

%environment
    export PATH=/opt/conda/bin:$PATH

%labels
    Author pvh@sanbi.ac.za
    Version 0.1+singularity1
```

You might notice that this uses OpenJDK 8 and does not have IGV in it. I found that Trimmomatic was crashing (with a core dump) with OpenJDK 11 (the version IGV requires).

**Comment by standage** [comment] 2019-08-30 13:40
Nice @pvanheus! In the couple years since I initially made this suggestion, Singularity has definitely come to the fore as a preferred alternative to Docker in many settings.

**Comment by jial2020** [comment] 2020-02-28 16:39
I used Singularity before, it is very convenient to allow people to run your genomic pipeline on any platforms, and easy to use because all files, commands and scripts were dumped to a container. But people still need to know how to do the scripts or shell commands, sometimes building the images is still struggling.

**Comment by twrightsman** [comment] 2023-04-28 18:45
Since there are now two options for setting up an isolated software environment for the genomics workshops (AMI and Conda) should we close this issue?

I would imagine additional issues could be opened up if there is any remaining desire for additional alternatives for setting up software environments, such as Docker or Singularity containers.

**Comment by ErinBecker** [comment] 2023-04-28 19:40
I support closing this issue.

**Closed** 2023-04-29 13:21 UTC
Labels: status:refer to cac
